name = "DataPicker"
uuid = "d0d4e46c-39cb-4708-b3c6-d9d4047ce5e1"
authors = ["Marcel Thielman <Marcel.Thielmann@uni-bayreuth.de>", "Boris Kaus <kaus@uni-mainz.de>"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
